Cosmosdb l100 examples
Azure/terraform pull request #100
Opened 2022-06-07 06:01 UTC by GinSiuCheng

Cosmos db sql level 100 examples 
- CosmosDB SQL API with auto-scale
- CosmosDB SQL API with manual scale
- CosmosDB SQL API with aad-rbac
- CosmosDB SQL API with analytical store 
- CosmosDB SQL API with server-side functionality
- CosmosDB SQL API with free-tier

@grayzu

2022-06-27 23:13 UTC, grayzu requested changes
Looks fantastic @GinSiuCheng. Just a few minor comments.

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-aad-rbac/main.tf
> +terraform {
To be consistent with other examples, please put the terraform and provider blocks in a separate file named "providers.tf".

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-aad-rbac/main.tf
> +}
Is there a minimum version of Terraform required for this? If not but you have tested it with a specific version, it should be added to ensure that it can be successful.

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-analyticalstore/main.tf
> +  required_providers {
same comments as above

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-autoscale/main.tf
> +  required_providers {
same comment as above.

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-free-tier/main.tf
> +  required_providers {
Same comment as above

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-manualscale/main.tf
> +  required_providers {
same as above.

2022-06-27 23:13 UTC, grayzu commented on quickstart/101-cosmos-db-serverside-functionality/main.tf
> +  required_providers {
same as above

2022-06-30 03:42 UTC, GinSiuCheng commented on quickstart/101-cosmos-db-aad-rbac/main.tf
> +}
3.X above should be used in this scenario as there are releases that impact some of these future samples.

2022-07-01 09:14 UTC, merged