Add examples for confidential VM, VMSS and OS Disk
Azure/terraform pull request #102
Opened 2022-06-22 10:14 UTC by myc2h6o

Adding examples for [Confidential VM](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#security_encryption_type), [Confidential VMSS](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine_scale_set#security_encryption_type) and [Confidential OS Disk](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#security_type)

2022-06-28 00:41 UTC, grayzu requested changes
Looks great! Thanks for the PR.

Few minor tweaks.

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-os-disk/provider.tf
> +terraform {
please rename your provider.tf files to providers.tf (with "s") to be consistent with documentation.

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-vm/variables.tf
> +  default     = "tftest"
Should leave this default off and make this a required parameter.

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-os-disk/variables.tf
> +  default     = "tftest"
Please leave this default value off and make this a required variable.

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-vm/main.tf
> +  size                = "Standard_DC2as_v5"
Why are we using this VM size? I do not necessarily have an issue with it but wondering why it was chosen.

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-vmss/main.tf
> +  sku                  = "Standard_DC2as_v5"
same

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-vmss/provider.tf
> +terraform {
same providers.tf

2022-06-28 00:41 UTC, grayzu commented on quickstart/201-confidential-vmss/variables.tf
> +  default     = "tftest"
same comment as above

2022-06-28 08:16 UTC, myc2h6o commented
Hi @grayzu thanks for reviewing the pr! I've resolved the comment, can you take another look?
To summary the update:
- renamed provider.tf to provider**s**.tf
- removed the default value for `name_prefix` and reorder the variables
- added doc link in comments for vm size and vmss sku `Standard_DC2as_v5`, to include the available sizes to use confidential vm

2022-06-28 09:58 UTC, myc2h6o commented on quickstart/201-confidential-vm/main.tf
> +  size                = "Standard_DC2as_v5"
there is limited size which can be used for confidential VM/VMSS. To avoid confusion, I've added the document link in the comment in the update.

2022-06-29 22:55 UTC, grayzu commented
Thanks @myc2h6o . Looks good to me now.

2022-06-29 22:56 UTC, merged