201-aks-rbac-dashboard-admin patch
Azure/terraform pull request #148
Opened 2023-02-13 03:36 UTC by lonegunmanb

This patch fix 201-aks-rbac-dashboard-admin, use identity instead of service principal.

2023-02-21 10:03 UTC, zioproto requested changes

2023-02-21 10:03 UTC, zioproto commented on quickstart/201-aks-rbac-dashboard-admin/azuread.tf
> -resource "azuread_service_principal" "default" {
The readme.md file has a table with the resources that should be updated.

2023-02-21 10:03 UTC, zioproto commented on quickstart/201-aks-rbac-dashboard-admin/kubernetes.tf
>  resource "kubernetes_cluster_role_binding" "dashboard" {
I am not familiar with this example. I dont understand why the kubernetes dashboard is not installed. Only this role-binding is created before installing the dashboard. 

The problem is that after running terraform the user would still have to run manually:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
``` 

But this conflicts with this role binding created via Terraform.

2023-02-21 10:03 UTC, zioproto commented on quickstart/201-aks-rbac-dashboard-admin/kubernetes.tf
>  resource "kubernetes_cluster_role_binding" "dashboard" {
This is what is installed via Terraform

```
% k get clusterrolebinding kubernetes-dashboard -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2023-02-21T09:44:21Z"
  name: kubernetes-dashboard
  resourceVersion: "1564"
  uid: 65eed073-a03b-416b-b802-239b9f540b18
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```

This is what installed by the Dashboard installed:

```
% k get clusterrolebinding kubernetes-dashboard -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"kubernetes-dashboard"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"kubernetes-dashboard"},"subjects":[{"kind":"ServiceAccount","name":"kubernetes-dashboard","namespace":"kubernetes-dashboard"}]}
  creationTimestamp: "2023-02-21T10:01:01Z"
  name: kubernetes-dashboard
  resourceVersion: "5563"
  uid: e9b28f41-730a-4ff3-a265-baf6f5733a3e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
```

2023-02-21 10:06 UTC, zioproto commented
I think the example should also install the dashboard with the desired configuration. Here the user experience is very bad, because creating the `ClusterRoleBinding` with Terraform the installation of the dashboard fails :( 
This has nothing to do with your PR, it was already broken.

2023-02-22 01:27 UTC, lonegunmanb commented
> I think the example should also install the dashboard with the desired configuration. Here the user experience is very bad, because creating the `ClusterRoleBinding` with Terraform the installation of the dashboard fails :( This has nothing to do with your PR, it was already broken.

Thanks @zioproto for your review. I think we can open an issue on the user experience improvement and leave it as another day's job.

2023-02-22 01:32 UTC, merged