201-vm-disk-encryption-extension patch
Azure/terraform pull request #152
Opened 2023-02-14 04:02 UTC by Pumpkin-3906

- Fix 201-vm-disk-encryption-extension example

2023-02-14 07:51 UTC, lonegunmanb requested changes
Thanks @Pumpkin-3906 for the update, I'd like to output the ssh private key via a key file so our users can ssh to the remove machine directly by using this file.

2023-02-14 07:51 UTC, lonegunmanb commented on quickstart/201-vm-disk-encryption-extension/outputs.tf
> +  value     = tls_private_key.vm_key.private_key_pem
Could we output this private key via a [`local_file` resource](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file)? And we'd better include `local` provider's version restriction in `terraform` block in `providres.tf` file.

2023-02-16 06:47 UTC, lonegunmanb requested changes

2023-02-16 06:47 UTC, lonegunmanb commented on quickstart/201-vm-disk-encryption-extension/main.tf
> +  filename = "id.rsa"
Please rename filename to `"id_rsa"`, thanks

2023-02-16 14:25 UTC, lonegunmanb requested changes

2023-02-16 14:25 UTC, lonegunmanb commented on quickstart/201-vm-disk-encryption-extension/main.tf
> +  content  = tls_private_key.vm_key.public_key_openssh
Please change to `content = tls_private_key.vm_key.private_key_pem`, thanks

2023-02-16 14:25 UTC, lonegunmanb commented on quickstart/201-vm-disk-encryption-extension/main.tf
> +  filename = "id_rsa"
Please rename filename to `key.pem` as we'll export private key in pem format, thanks.

2023-02-17 01:12 UTC, lonegunmanb requested changes
@Pumpkin-3906 the content of key file is incorrect, please read the comment carefully, thanks.

2023-02-17 01:12 UTC, lonegunmanb commented on quickstart/201-vm-disk-encryption-extension/main.tf
> +  content  = tls_private_key.vm_key.public_key_pem
Should be:

```hcl
content  = tls_private_key.vm_key.private_key_pem
```

2023-02-17 01:37 UTC, Pumpkin-3906 commented on quickstart/201-vm-disk-encryption-extension/main.tf
> +  content  = tls_private_key.vm_key.public_key_pem
Fixed. Thank you.

2023-02-17 04:59 UTC, lonegunmanb approved these changes
Thanks @Pumpkin-3906, LGTM.

2023-02-17 04:59 UTC, merged