User Story 60501: cdn-with-custom-origin
Azure/terraform pull request #195
Opened 2023-03-18 19:51 UTC by TomArcherMsft

Part of POC to test generating sample code and articles using OpenAI.

2023-03-18 19:52 UTC, TomArcherMsft commented
@grayzu @lonegunmanb This sample is ready for review.

2023-03-20 01:42 UTC, lonegunmanb approved these changes
Thanks @TomArcherMsft for opening this pr! LGTM, but I'd like to ask @grayzu for a further review.

2023-03-21 00:13 UTC, grayzu requested changes
Looking Fantastic!

Couple of minor comments.

2023-03-21 00:13 UTC, grayzu commented on quickstart/101-cdn-with-custom-origin/readme.md
> +| `origin_url` | Url of the origin. | null |
Looks like you do have a default for this.

2023-03-21 00:13 UTC, grayzu commented on quickstart/101-cdn-with-custom-origin/outputs.tf
Should probably output the CDN endpoint FQDN as well.

2023-03-28 00:16 UTC, TomArcherMsft commented
@grayzu @lonegunmanb I've made the fixes.

2023-03-29 19:27 UTC, grayzu commented
Kicking off tests. If they pass and @lonegunmanb does not have any issues, this should be good to merge.

2023-03-30 16:43 UTC, merged