User Story 60501: 101-ddos-protection-plan
Azure/terraform pull request #202
Opened 2023-03-25 18:14 UTC by TomArcherMsft

Part of POC to test generating sample code and articles using OpenAI.

2023-03-26 00:40 UTC, lonegunmanb approved these changes
Thanks @TomArcherMsft for opening this pr! LGTM 🚀. @grayzu any suggestions?

2023-03-27 23:53 UTC, grayzu requested changes
Thanks for the PR!

Minor comment regarding the readme but otherwise looks fantastic!

2023-03-27 23:53 UTC, grayzu commented on quickstart/101-ddos-protection-plan/readme.md
> +| `virtual_network_name` | Specify a DDoS virtual network name. | null |
These variables do not exist so should be removed from readme.

2023-03-28 00:22 UTC, TomArcherMsft commented
@grayzu I've removed the readme file's reference to the unused variables.

2023-03-29 19:18 UTC, grayzu commented
Running tests now. Assuming they go well, this is good to merge.

2023-04-11 19:55 UTC, merged