User Story 95456
Azure/terraform pull request #227
Opened 2023-05-26 18:38 UTC by TomArcherMsft

[User Story 95456](https://dev.azure.com/msft-skilling/Content/_workitems/edit/)

2023-05-26 23:45 UTC, TomArcherMsft commented
@grayzu @lonegunmanb @stemaMSFT The `azure-vote.yaml` file is used in the article to deploy an application.

2023-05-27 02:11 UTC, lonegunmanb approved these changes
Thanks @TomArcherMsft, LGTM!

2023-05-28 00:46 UTC, lonegunmanb approved these changes
Thanks @TomArcherMsft, LGTM!

2023-05-31 01:34 UTC, grayzu requested changes
Thanks for the PR!

Looks mostly good. One minor change.

2023-05-31 01:34 UTC, grayzu commented on quickstart/201-k8s-cluster-with-tf-and-aks/variables.tf
>  variable "msi_id" {
This should be included in the readme file.

2023-05-31 15:14 UTC, stemaMSFT commented
@grayzu I think after Tom's change we're just waiting on the E2E test. Can you kick it off?

2023-06-01 01:54 UTC, lonegunmanb approved these changes
LGTM!

2023-06-01 19:24 UTC, stemaMSFT commented
Are we good to merge this PR?

2023-06-01 19:54 UTC, TomArcherMsft commented
@stemaMSFT The pattern with Mark/Zijie has been that once they both have verified the code, Zijie responds with LGTM (or similar) and Mark merges. Therefore, since Zijie has given his "LGTM" comment, I would think you're okay to merge.

2023-06-01 21:02 UTC, merged