Added 101-1vm-2nics-2subnets-1vnet
Azure/terraform pull request #37
Opened 2019-11-12 17:15 UTC by kpatnayakuni

I have picked up an ARM template '101-1vm-2nics-2subnets-1vnet' from azure-quickstart-templates and created terraform configuration for the same.

2019-11-12 17:15 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/terraform?pullRequest=37) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/terraform?pullRequest=37) before we can accept your contribution.<br/><br/>:x: kpatnayakuni [sign now](https://cla.opensource.microsoft.com/Azure/terraform?pullRequest=37)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/terraform?pullRequest=37) it.</sub>

2019-12-02 23:49 UTC, grayzu requested changes
Looks great, @kpatnayakuni!! Thanks for the PR. 
Can you please update the syntax to 0.12 syntax by removing all of the unnecessary "${ , }" around the variables? Otherwise it is good to go.

2019-12-03 02:55 UTC, kpatnayakuni commented
Thanks, @grayzu for reviewing my PR, I have updated the configuration to v0.12.16 and request you to review again. Thank you.

2019-12-05 00:49 UTC, grayzu approved these changes
Thanks @kpatnayakuni !

I commented on few minor tweaks that would be great but approving regardless.

2019-12-05 00:49 UTC, grayzu commented on quickstart/101-1vm-2nics-2subnets-1vnet/readme.md
> +| zurerm_virtual_network | One Virtual Network |
minor typo. Missing "a"

2019-12-05 00:49 UTC, grayzu commented on quickstart/101-1vm-2nics-2subnets-1vnet/variables.tf
> +
Should add the version here for best practices.

2022-11-17 22:59 UTC, closed without merging