Update the Terraform Azurerm Provider Resource Contribute.md
Azure/terraform pull request #51
Opened 2020-06-23 02:33 UTC by yupwei68

1. Terraform code style, code sample, variable definition and corresponding code reference link has changed. We need to refresh and update the content to guide how to contribute to Azurerm Provider
2. Test with local build is not exactly how it works, I have changed to how it works now.

2020-06-23 06:34 UTC, WodansSon requested changes
@yupwei68, thank you so much for this PR, this look fantastic! 🚀 I have left a couple of minor comments on the PR for you to consider... but, other than that this is good stuff! Thanks so much!

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Terraform is developed using Go Programming Language. You need to install Go Programming Language **1.x.x** to be able to build and debug the provider locally.
```suggestion
Terraform is developed using Go Programming Language. You need to install Go Programming Language **1.x.x** to be able to build and debug the provider locally. You can check to see what version of Go is currently being used in the project by checking the [go.mod](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/go.mod) file in the root directory.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Then you can go to your terraform test folder where `main.tf` exists and inialize your terraform working directory by `terraform init`.
```suggestion
Then you will need to go to your terraform test folder where the `main.tf` configuration file exists and initialize your terraform working directory by using the `terraform init` command.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Data sources, resources and tests are defined in the [azurerm](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services) folder of the repository.
```suggestion
Data sources, resources and tests are defined in the [azurerm/internal/services](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services) folder of the repository.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +AzureRM Terraform provider uses the [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) to interact with Azure. It's important that you respect that rule. If you are trying to do something
```suggestion
AzureRM Terraform provider uses the [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) to interact with Azure. It's important that you respect that rule. If you are trying to do something that is not available in the Azure SDK for Go, then you should check if the API is availble in [Azure Service Repository](https://github.com/Azure/azure-rest-api-specs) and open an issue in the **Azure SDK for Go** repository to have it added to a future release of the Azure SDK for Go.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +All the imports for the Azure Go SDK services have to be done in the [client.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/clients/client.go) file
```suggestion
All the imports for the Azure SDK for Go services have to be done in the [client.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/clients/client.go) file. It exposes a top level struct, `Client` that exposes all the service clients that you may use in a data source or resource to interact with Azure. If the service already exist and you are just modifying an existing resource you can skip this step.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +2. Go to your corresponding service folder [batch](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services/batch) and write a `client.go` in client fol
```suggestion
2. Go to your corresponding service folder [batch](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services/batch) and write a `client.go` in client folder. If the service folder does not exist, you will need to create one.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +The file for a data source is named following the convention: *NAME_OF_THE_DATA_SOURCE*_data_source.go.
```suggestion
When naming a new data source file it should follow the below naming convention:
**name_of_the_data_source**_data_source.go

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Once your data source is defined, you need to register it into data sources map in the `registration.go` file:
```suggestion
Once your data source is defined, you need to register it into the data sources map in the `registration.go` file:

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +- The file is named using the convention: *NAME_OF_RESOURCE*_resource.go
```suggestion
- The file is named using the convention: *name_of_resource*_resource.go

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Acceptance tests are test that will run live on your Azure subscription to validate that your data source or resource is working well. Each data source should have its acceptance tests and each resou
```suggestion
Acceptance tests are tests that will run live on your Azure subscription to validate that your resource/data source is working as expected. Each resource/data source should have its own set of acceptance tests that will run independently of each other.

```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Tests are definied in the `test` directory, aside with data sources and resources. The file name is the same than the one for the data source or resource, with the `_test` suffix.
```suggestion
All tests for a given resource/data source are located in the `test` folder which is a sub folder of the service folder. The file name for the tests will be exactly the same as the resource/data source with the addition of the `_test.go` suffix. For example, if you created a data source for `batch account`, the data source file would be named **batch_account_data_source.go** and the test file would have the name **batch_account_data_source_test.go**.
```

2020-06-23 06:34 UTC, WodansSon commented on provider/CONTRIBUTE.md
> +Please refer to the above section to learn on to run the acceptance tests on your laptop.
```suggestion
Please refer to the above section to learn how to run the acceptance tests on your computer.

```

2020-06-23 19:29 UTC, TomArcherMsft commented
@yupwei68 This looks fine to me. The only change I would suggest is to change the anchor text where you're using verbiage like "this page". I would recommend using the actual product being installed as the anchor text. f

2020-06-28 02:13 UTC, yupwei68 commented
Hi @WodansSon @TomArcherMsft Thanks for your comments. Corresponding changes have been pushed. Please continue reviewing.

2020-07-27 03:43 UTC, WodansSon approved these changes
@yupwei68, thanks for pushing those changes, this LGTM now! 🚀

2020-07-27 03:45 UTC, merged